/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'naver' at '14. 9. 12 오후 6:20' with Gradle 1.11
 *
 * @author naver, @date 14. 9. 12 오후 6:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
